# Generated by Django 3.2.9 on 2021-12-14 14:14

from django.db import migrations


def default_data_for_category(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Category = apps.get_model("blog", "Category")
    data = [
        {"name": "Default", "slug": "default"},
        {"name": "Daily", "slug": "daily"},
        {"name": "Tech", "slug": "tech"},
    ]
    for d in data:
        c = Category(**d)
        c.save()


class Migration(migrations.Migration):

    dependencies = [("blog", "0001_initial")]

    operations = [migrations.RunPython(default_data_for_category)]

