# Generated by Django 4.0 on 2022-01-18 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blog', '0002_auto_20211214_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='auth.user'),
        ),
    ]
